cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
language: python
python:
  - "3.6"

script:
  # wait 30 m
  - if [[ "$TRAVIS_COMMIT_MESSAGE" =~ "Deploy Unpublished/GithubTrending" ]]; then sleep 9m; echo "wait"; sleep 9m; echo "wait"; sleep 9m; echo "wait"; fi
  - date > date
  - travis_retry python scraper.py

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  target_branch: trends
  on:
    branch: trends